spring.application.name=HotelBookingService

spring.datasource.url=jdbc:postgresql://localhost:5432/hotel_booking
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# --- JWT ---
jwt.secret=${JWT_SECRET:NDA0RTYzNTI2NjU0NmE1NzZlNWE3MjM0NzUzNzc4MjE0MTI1NDQyQTQ3MkQ0QjYxNTA2NDUzNjc1NmQ1ODAw}
jwt.expiration-ms=3600000
